src/App.js, src/components/SinglePlantSpecies.js, src/pages/PlantDatabase.js, src/pages/PlantSpecies.js, src/pages/PlantUsernameSpecies.js
'&indoor=1' param filtering only indoor plants was still returning 13 pages of data. 
So I changed my approach and tried:
1. Query Plant List API with plant species name and get array of plants that match that species
2. extract ID of these plants and get one single ID out of list. 
3. Query Plant Details API with ID to get details about single plant
I think my code works  but I'm not sure because the API that returns one single plant by ID has stopped working and is now asking me to upgrade.
=> Plantspecies

src/App.js, src/pages/Login.js, src/pages/NotFound.js, src/pages/UserProfile.js, src/reducers/plants.js, src/reducers/user.js, src/utils/BackendUrl.js
Register and login functionalities working 
NEXT UP: moving registering to new page & creating registration form
=> register &login work, both from login page

.gitignore, package-lock.json, package.json, src/components/SinglePlantSpecies.js, src/pages/PlantDatabase.js, src/pages/PlantUsernameSpecies.js, src/pages/UserGarden.js, src/utils/BackendUrl.js
=> security added

src/components/Weather.js, src/pages/Login.js, src/pages/UserGarden.js, src/pages/UserProfile.js
- Weather moved to its own component
- User Garden page working 
- Minor bug fixes (ie: weather API was being called multiple times by mistake)
=> User garden

src/components/AddPlant.js, src/pages/PlantProfile.js, src/pages/UserGarden.js, src/reducers/plants.js
Fixes: 
- addPlant working, 
- Garden bug fixed, 
- Plant slice fine tuned,
- Plant profile started
=> Add plant branch ready for merge 

package-lock.json, package.json, src/App.js, src/components/AddPlant.js, src/pages/Login.js, src/pages/PlantProfile.js, src/pages/UserGarden.js, src/pages/UserProfile.js, src/reducers/plants.js
- Fixed routes in App.js, 
- Added functionality to go from garden to single plant profile, 
- Creared single plant profile pages,
- Also edited Plant slice to add reducers for Plant details
=> SinglePlant functionalities 

src/App.js, src/components/AddPlant.js, src/components/Nav.js, src/components/Weather.js, src/index.css, src/pages/LandingPage.js, src/pages/PlantProfile.js, src/pages/UserGarden.js, src/pages/UserProfile.js
created basic styling in index.css for deployed version
=> index.css  - styling added

src/pages/Login.js, src/pages/PlantProfile.js
Delete plant button works, However "navigate to previous page" inside delete button doesn't work
=> added plant delete button

package-lock.json, package.json, src/components/AddPlant.js, src/pages/UserGarden.js
- added a function in garden that updates the plantitem-state with spread operator
- passed the function into the addplant-component as a param
- edited the onformsubmit-function in addplant-component slightly
- added comments
=> Automatic garden update

src/pages/PlantProfile.js, src/reducers/plants.js
- delete plant works  
- delete plant updates redux state
- delete plant  brings user back to their garden
=> delete plant updates state and brings user back to their garden

src/pages/Login.js, src/pages/PlantDatabase.js, src/pages/PlantProfile.js, src/pages/PlantSpecies.js, src/pages/PlantUsernameSpecies.js, src/pages/Register.js, src/pages/UserGarden.js
back button added to pages where it made sense
=> added back buttons

package-lock.json, package.json, src/pages/EditPlantProfile.js, src/pages/PlantProfile.js, src/reducers/plants.js
- changed birthday field to date input
- added file upload functionality in patch request
- added file input field
=> Image upload

src/components/PlantList.js, src/pages/PlantDatabase.js
- created buttons tied to variables in Plant Database page (that we can rename to next baby plant inspo page or something"
- when you click a button (for example "indoor") it create a ransom list of indoor plants
- from the list you click on a plant and you see plant species profile
=> plant inspiration page works but returns duplicate name plants

src/components/Loading.js, src/components/Nav.js, src/components/NewTask.js, src/components/PlantList.js, src/pages/EditPlantProfile.js, src/pages/EditUserProfile.js, src/pages/Login.js, src/pages/PlantDatabase.js, src/pages/PlantProfile.js, src/pages/PlantSpecies.js, src/pages/PlantUsernameSpecies.js, src/pages/ToDo.js, src/pages/UserGarden.js, src/pages/UserProfile.js
Restructure:
- nav bar cleaned up
- moved todo list inside user profile page
- moved plant inspiration page to user garden
- moved delete plant  to edit plant page
-moved delete user  to edit profile page
Bugs:
-added accesstoken security to all pages
-fixed loading in plant inspo page
=> Restructure of pages + bug fixes

src/pages/EditUserProfile.js, src/pages/UserProfile.js, src/reducers/user.js
- added city & level & bio to redux store user slice
- created city & level & bio reducers
- added city & level & bio to User profile page 
- added city & level & bio edit items in edit profile page
=> Updated user info

src/pages/EditPlantProfile.js, src/pages/PlantProfile.js
- dates fixed in plant profile page
- last watered last soil change work in editplantprofile
=> Plantdates

src/components/AddPlant.js, src/components/Weather.js, src/index.css, src/pages/PlantProfile.js, src/pages/UserGarden.js, src/styling/Buttons.css, src/styling/Garden.css, src/styling/PlantProfile.css, src/styling/Weather.css
- moved styling from index.css into separate files
- changed weather slightly
- continued with garden styling
=> Garden, weather and plant profile styling

src/components/Weather.js, src/pages/UserGarden.js, src/styling/Garden.css, src/styling/Weather.css
- made entire single plant div in garden a link to plant's profile
- added species underneath plantname
- changed weather to text only
- styled plant inspo section
=> Change structure of garden & style of weather

src/pages/UserGarden.js
- added handleAddPlant-function to dependency array of useEffect-hook that fetches garden
=> Garden re-renders on new plant

src/index.css, src/pages/EditPlantProfile.js, src/pages/UserGarden.js, src/styling/App.css, src/styling/Garden.css, src/styling/Login.css, src/styling/Nav.css
- changed navbar position to sticky instead of fixed
- changed navbar links color
- removed labels and added placeholders to date and file inputs in edit plant
- change background on mobile
=> Miscellaneous styling
